### ISSUE TITLE
suggestion: stop using enums

### ISSUE THREAD

**Issue by lifeiscontent** [malthe/ts-postgres#100]
enums have a runtime cost to them and are generally pretty clunky to use in certain situations, might want to opt for objects and create types from them so they're easier to use.

e.g.

```
const foo = {a: 'b'} as const; // ReadOnly<{a: 'b'}>
type Foo = typeof foo;
type FooUnion = Foo[keyof Foo];
```

if you want better tree shaking support you could use individual exports also

```
export foo = 'a';
export bar = 'b';
```

```
// usage
import * as ns from './somewhere';

ns.foo
ns.bar
````

**Comment by malthe** [comment]
This has largely been fixed by #114 and #115.
