### ISSUE TITLE
use Record<string, string | undefined> for environment

### ISSUE THREAD

**Issue by lifeiscontent** [malthe/ts-postgres#101]
just wanted to say I love what you're doing!

I spent some time building something similar but haven't had the time to finish it, great work!

https://github.com/malthe/ts-postgres/blob/66a77cabdcaf9fa861c7a8711f8adf592f867c6c/src/defaults.ts#L27

you'll notice a couple of issues with the code if you use Record<string, string | undefined> it follows the same protocol as process.env so you won't need to cast `env` to `Environment` and you'll uncover a couple of parse issues when these keys are undefined for what its worth, I've found using `as` hides bugs and avoiding in where possible will result in better code quality.

**Comment by malthe** [comment]
I have changed it so that it still uses `Environment` (which I think is important for documentation reasons), but in a different way which avoids the `as unknown as` cast.
