### ISSUE TITLE
Cannot create a Query() object

### ISSUE THREAD

**Issue by rlaveycal** [malthe/ts-postgres#111]
I get syntax errors when trying to create a `Query` instance in a ES Module

```ts
import { type Query } from 'ts-postgres'
const q = new Query('select 1;')
```

gives `'Query' only refers to a type, but is being used as a value here.ts(2693)`

If I don't have the `type` on the import then that also causes an error:

`'Query' is a type and must be imported using a type-only import when 'verbatimModuleSyntax' is enabled.ts(1484)`

**Comment by malthe** [comment]
@rlaveycal that's because a `Query` is [specified as an interface](https://malthe.github.io/ts-postgres/interfaces/Query.html).

That is, you can just do `{text: 'select 1'}` and that is your query.

**Comment by rlaveycal** [comment]
How do you pass the values?

The README gives the example

```
const query = new Query("SELECT 'Hello ' || $1 || '!' AS message", ['world']);
```

but the `Query` interface only has a `text` member + `QueryOptions` which doesn't have a `values`

**Comment by malthe** [comment]
Thanks for finding this documentation issue – it was changed in 1.7 to an interface rather than a class.

The example is no longer valid because `values` aren't part of a query anymore. Instead, simply use:
```typescript
const result = await client.query('select $1', [1]); 
// or const result = await client.query('select 1');
// or const result = await client.query({text: 'select 1'});
```
Values (if needed) are always specified as the second parameter to `Client.query`.

**Comment by rlaveycal** [comment]
Ah OK - I'll stop trying to make it do something it's not intended to! 😁

**Comment by malthe** [comment]
Thanks for reporting this.
