### ISSUE TITLE
Benchmark ts-postgres VS popular postgres Library

### ISSUE THREAD

**Issue by cesco69** [malthe/ts-postgres#117]
Add yuor library into
https://github.com/porsager/postgres-benchmarks

**Comment by malthe** [comment]
I have contributed https://github.com/porsager/postgres-benchmarks/pull/9 which adds ts-postgres to the benchmark suite.

There are some preliminary results included in the description there.

That said, I'll restate Rasmus Porsager's note here:

> NB. In daily usage it is very likely that this difference doesn't matter as much since the time spent by the client library is negligable compared to the query time itself.

The merits of the various libraries come down to your requirements.

**Comment by cesco69** [comment]
@malthe Thanks! I'm evaluating different libs. Just a suggestion, take a look at "pg-native"

https://github.com/brianc/node-pg-native/blob/master/index.js

I think with your pipeline support and native driver from "pg-native", you can reach the best performance
