### ISSUE TITLE
SSL is always off for me

### ISSUE THREAD

**Issue by matthewnourse** [malthe/ts-postgres#118]
...I think because of these lines in `client.ts`:

```
    const ssl =
            (
                this.config.ssl ??
                ((DEFAULTS.sslMode as SSLMode) || SSLMode.Disable) ===
                    SSLMode.Disable
            ) ?
                SSLMode.Disable
            :   { mode: SSLMode.Prefer, options: undefined };
```

Seems to me that if `this.config.ssl` is truthy then `ssl` will be set to `SSLMode.Disable`.  Also, `DEFAULTS.sslMode` is `undefined` for me, not sure why.

If I change the parentheses to 

```
    const ssl = this.config.ssl ??
            (((DEFAULTS.sslMode as SSLMode) || SSLMode.Disable) ===
                    SSLMode.Disable
            ) ?
                SSLMode.Disable
            :   { mode: SSLMode.Prefer, options: undefined });
```

...and I set `ssl` in my `config` then `ts-postgres` tries to connect using SSL.

I hope this helps, and thank you for your work on `ts-postgres`.

**Comment by malthe** [comment]
The way it should work _without_ any configuration is that the library prefers to make a secure connection.

That is, if your database is capable of securing the connection, then that's what should be happening by default. You only really need to set the configuration if you want to explicitly _disable_ this, or _require_ it.

There was also some discussion on this configuration in #112.

I think it's reasonable to say that it's a little complicated to get it right if you do manually configure this. The `DEFAULT.sslMode` variable is populated from an environment variable setting – `PGSSLMODE`.

**Comment by matthewnourse** [comment]
Thanks @malthe for your super-fast response and for the tip about `PGSSLMODE` and `Client.encrypted`.  Unfortunately I don't get as far as being able to check `Client.encrypted` because I don't get a connection at all- the database I am trying to connect to is SSL-only.

If I set `PGSSLMODE=prefer` and *do not* set `config.ssl` then `ts-postgres` makes an SSL connection- so far so good.

But if I set `PGSSLMODE` and *do* set `config.ssl` then `ts-postgres` does not attempt to make an SSL connection so is rejected by the server.

My test program is:
```
import { SSLMode, connect } from 'ts-postgres';

const connectDb = async () =>
  connect({
    host: '127.0.0.1',
    port: 5432,
    user: 'ssltestuser',
    password: 'password',
    database: 'postgres',
    ssl: { mode: SSLMode.Prefer, options: undefined },
  });

connectDb().then((db) => db.query('SELECT 1').then(console.log).then(() => process.exit(0)));
```

Here's its output:

```$ env PGSSLMODE=prefer NODE_TLS_REJECT_UNAUTHORIZED=0 node ts_pgsql_connect.js
ts-postgres: Error: no pg_hba.conf entry for host "127.0.0.1", user "ssltestuser", database "postgres", no encryption: undefined
/home/matt/tmp/test/ts_pgsql_connect/ts_pgsql_connect.js:2165
            throw new Error(`${error2.message}: ${error2.detail}`);
                  ^

Error: no pg_hba.conf entry for host "127.0.0.1", user "ssltestuser", database "postgres", no encryption: undefined
    at ClientImpl.handle (/home/matt/tmp/test/ts_pgsql_connect/ts_pgsql_connect.js:2165:19)
    at Socket.<anonymous> (/home/matt/tmp/test/ts_pgsql_connect/ts_pgsql_connect.js:1619:27)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Readable.push (node:internal/streams/readable:253:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v20.5.1
```

However if I comment out the `ssl: ` line then `ts-postgres` successfully connects:

```
$ env PGSSLMODE=prefer NODE_TLS_REJECT_UNAUTHORIZED=0 node ts_pgsql_connect.js
(node:12011) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.
(Use `node --trace-warnings ...` to show where the warning was created)
Result {
  names: [ '?column?' ],
  rows: [ ResultRowImpl(1) [ 1 ] ],
  status: 'SELECT 1'
}
```

Just for comparison, here's how `psql` behaves:
```
$ env PGSSLMODE=disable psql --user ssltestuser --host 127.0.0.1 postgres -c 'select 1'
psql: error: connection to server at "127.0.0.1", port 5432 failed: FATAL:  no pg_hba.conf entry for host "127.0.0.1", user "ssltestuser", database "postgres", no encryption
$ env PGSSLMODE=prefer psql --user ssltestuser --host 127.0.0.1 postgres -c 'select 1'
Password for user ssltestuser:
 ?column?
----------
        1
(1 row)
```

**Comment by matthewnourse** [comment]
...and if I don't set `PGSSLMODE` and leave `ssl: ` commented out then I get rejected again:

```
$ env NODE_TLS_REJECT_UNAUTHORIZED=0 node ts_pgsql_connect.js
ts-postgres: Error: no pg_hba.conf entry for host "127.0.0.1", user "ssltestuser", database "postgres", no encryption: undefined
/home/matt/tmp/test/ts_pgsql_connect/ts_pgsql_connect.js:2165
            throw new Error(`${error2.message}: ${error2.detail}`);
                  ^

Error: no pg_hba.conf entry for host "127.0.0.1", user "ssltestuser", database "postgres", no encryption: undefined
    at ClientImpl.handle (/home/matt/tmp/test/ts_pgsql_connect/ts_pgsql_connect.js:2165:19)
    at Socket.<anonymous> (/home/matt/tmp/test/ts_pgsql_connect/ts_pgsql_connect.js:1619:27)
    at Socket.emit (node:events:514:28)
    at addChunk (node:internal/streams/readable:343:12)
    at readableAddChunk (node:internal/streams/readable:316:9)
    at Readable.push (node:internal/streams/readable:253:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)

Node.js v20.5.1
```

**Comment by matthewnourse** [comment]
...and if I patch the compiled `client.js` with the parentheses changes as described in my first comment, `ts-postgres` will use an SSL connection even if I don't define `PGSSLMODE`.

**Comment by malthe** [comment]
I think `{ mode: SSLMode.Prefer, options: undefined }` should be correct and work as expected – as exactly the default setting. Must be a bug.

**Comment by malthe** [comment]
@matthewnourse no don't worry about it, I'll get it sorted asap based on your input.

**Comment by malthe** [comment]
This should be fixed now – available to try locally using the [build artifact](https://github.com/malthe/ts-postgres/actions/runs/8660683715/artifacts/1408296760).

**Comment by matthewnourse** [comment]
Works for me, thanks for the fast fix!
