### ISSUE TITLE
Export DatabaseError, ErrorLevel, and TransactionStatus as values

### ISSUE THREAD

**Issue by azerum** [malthe/ts-postgres#120]
[Currently](https://github.com/malthe/ts-postgres/blob/b96959423ae70fdb2d2abad4b4fd797c8ffe549f/src/index.ts#L31) `DatabaseError` is exported with `export type`, which means that the users of the library cannot import the class of `DatabaseError` itself to do `instanceof` checks

The following (example) code breaks at runtime when compiled to either ESM or CommonJS:

```ts
import { DatabaseError } from 'ts-postgres'

try {
    throw new Error()
}
catch (error) {
    if (error instanceof DatabaseError) {
        console.log('Unexpected')
    }
}
```

ESM error:

```
import { DatabaseError } from 'ts-postgres';
         ^^^^^^^^^^^^^
SyntaxError: The requested module 'ts-postgres' does not provide an export named 'DatabaseError'
```

Similarly, one might want to access enums `ErrorLevel` and `TransactionStatus`, but at runtime those cannot be imported due to `export type`

**Comment by malthe** [comment]
I do question doing this for `ErrorLevel` and `TransactionStatus` – these are both `const enum` and being exported as `type` should not prevent you from accessing their fields and compare them to the enum values, e.g. `client.transactionStatus === TransactionStatus.Idle`.

This should be an integer comparison where the symbol `Idle` is defined only in the type definition.

**Comment by azerum** [comment]
Turns out some tools don't play well with `const enum`, example is `vitest` testing framework, which uses `vite` for code building, which uses `esbuild`

[This comment](https://github.com/evanw/esbuild/issues/2298#issuecomment-1146378367) was helpful for my understanding. Essentially, TypeScript compiler looks at enums in `d.ts` files to decide what number to replace `TransactionStatus.Idle` occurrences in code. This contradicts one expectation about TypeScript: that `d.ts` files and types in general do not affect the emitted JS code

`esbuild` relies on such assumption, so it does not check `d.ts` files at all

Hence when running [this test](https://github.com/azerum/ts-postgres-const-enum/blob/60f9f4bee5b47bace325de01f05290654ec153af/src/enum.test.ts) in vitest, the TS code is compiled to roughly this JS code:

```js
import { TransactionStatus, connect } from "ts-postgres";
import { expect, test } from "vitest";
test("Initially, transactionStatus is Idle", async () => {
  const client = await connect({
    database: "postgres"
  });
  expect(client.transactionStatus).toBe(TransactionStatus.Idle);
});
```

Where `TransactionStatus.Idle` is not replaced (since `d.ts.` files are not checked). If exported as type, `TransactionStatus` does not exist at runtime, so we get error in the test:

```
TypeError: Cannot read properties of undefined (reading 'Idle')
```

# When exporting as value

I've created a repository with two commits: one uses `ts-postgres` version which exports `TransactionStatus` as type, and other - which exports it as value. I've compiled code with tsc, esbuild, and run a vitest test and compared behavior

Here's the repository: https://github.com/azerum/ts-postgres-const-enum

You can see the README.md for results (tsc/esbuild output, esbuild runtime behavior, vitest output)

In short, when exporting TransactionStatus as value, TypeScript generates this code in `dist/module/protocol.js`:

```js
export var TransactionStatus;
(function (TransactionStatus) {
    TransactionStatus[TransactionStatus["Idle"] = 73] = "Idle";
    TransactionStatus[TransactionStatus["InTransaction"] = 84] = "InTransaction";
    TransactionStatus[TransactionStatus["InError"] = 69] = "InError";
})(TransactionStatus || (TransactionStatus = {}));
```

This happens because you have `isolatedModules: true` in your tsconfig.json, and it implies default value `preserveConstEnums: true` (https://www.typescriptlang.org/tsconfig#preserveConstEnums)

This allows vitest test to pass and esbuild-built code to run. Yet, when the user of the library compiles code with regular tsc, inlining is still applied (see `npm run build:tsc` in the [readme](https://github.com/azerum/ts-postgres-const-enum#export-value))

# 

The only disadvantage of const-enum + preserveConstEnums I see is increased emitted code size. I thing it's a better trade-off to support widely used `vitest`, `vite`, `esbuild`

**Comment by malthe** [comment]
The change to `const enum` was actually motivated by #100 – but it had not occurred to me that they're actually against that core tenant of TypeScript, that it should not rely on type-directed emit.

I think the solution is to drop the use of enums as a public interface since they're inefficient without their `const enum` variant in the sense that they unnecessarily contribute to code bloat.

It would seem that a simple constant assignment such as `TransactionStatusIdle = 0x49` is preferable, instead letting TypeScript help with a fixed set of valid constants for a particular value:
```python
type TransactionStatus = TransactionStatusIdle | TransactionStatusInTransaction | ...
```
A stricter solution would be the use of symbols I suppose, but this seems unnecessary to me.

**Comment by azerum** [comment]
Thanks for sharing the idea 

I don't use enums often, and the issue #100 does not specify concrete examples of when enums are inefficient. Are they problematic because of the increased emitted code size? Or because they compile to functions that construct an object with potentially many keys? Have enums ever caused issues in practice?

# 

The solution with constants would be along a lines of this?

```ts
export const TransactionStatusIdle = 0x49
export const TransactionStatusInTransaction = 0x54
export const TransactionStatusInError = 0x45

export type TransactionStatus = 
    | typeof TransactionStatusIdle
    | typeof TransactionStatusInTransaction
    | typeof TransactionStatusInError
```

Given the TransactionStatus- prefix, the constants are unlikely to clash. The users could also inspect the `client.transactionStatus` property to see its TS type. One can also discover possible values via autocomplete. So it seems fine

It might be inconvenient to convert large enum, such as `DataType`, to such syntax, but writing convenience is perhaps not the most important criteria

**Comment by malthe** [comment]
Yes, I think the point is exactly that the inconvenience isn't so bad, and the detriment in using enums is significant, in terms of code size and misalignment with a core TypeScript tenant.

**Comment by azerum** [comment]
Stumbled upon this by accident, it's been a while! Out of curiosity, I compare all options here:

- Constants + union type
- Enum
- Object

I excluded options:

- `const enum` with `preserveConstEnum: false` - breaks `vitest`, `esbuild`

- `const enum` with `preserveConstEnum: true` - compiles to the same code as `enum` and seems to type check the same

#### Feature comparison:

| Feature                 | Constants          | Enum                  | Object               |
|-------------------------|------------------|---------------------|--------------------|
| Creates object           | ❌                 | ✅                   | ✅                  |
| Nominal                  | ❌*                | ✅                   | ❌*                 |
| Assignable from number   | ✅**                 | ✅                   | ✅**                  |
| Iterable values          | ❌                 | ✅                   | ✅                  |
| Reverse mapping          | ❌                 | ✅                   | ❓***                  |

- `*` - perhaps can be emulated with type tricks

- `**` - will be "no" if `*` is used

- `***` - users can construct it

#### Features explanation:

- Does it create object at runtime?

- Is it a nominal type? E.g. `enum` is nominal, you can't assign one enum to another:

```ts
enum A { A = 1 }
enum B { A = 1 }

function f(a: A) {}

f(B.A) // error
```

- Can a plain number to be assigned to it? E.g. yes for `enum` (so it's technically not quite nominal)

```ts
enum A { A = 1 }
const a: A = 1 // no error
```

- Can iterate values at runtime?

```ts
enum A { A = 1, B = 2 }

for (const key of A) {
    // 'A'
    // 'B'
    console.log(key)
}
```

- Can reverse-map value to name?

```ts
enum A { A = 1, B = 2 }

console.log(A[1]) // 'A'
```

#### How to implement: Constants 

```ts
export const TransactionStatusIdle = 0x49
export const TransactionStatusInTransaction = 0x54
export const TransactionStatusInError = 0x45

export type TransactionStatus = 
    | typeof TransactionStatusIdle
    | typeof TransactionStatusInTransaction
    | typeof TransactionStatusInError
```

#### How to implement: Object 

```ts
const TransactionStatus = {
    Idle: 0x49,
    InTransaction: 0x54,
    InError: 0x45,
}

type ValueOf<T> = T[keyof T]

type TransactionStatus = ValueOf<typeof TransactionStatus>

// Side note: exporting like this helps with rename refactoring - both type
// and value are renamed together; when exported separately, VSCode renames 
// just one and then it's hard to rename the other
export { TransactionStatus }
```
