### ISSUE TITLE
Migration to version 2.0.3

### ISSUE THREAD

**Issue by eugeneK1968** [malthe/ts-postgres#125]
Hello there.
I am trying to make migration from version 1.2.1 to 2.0.3. In the process of my tests I have encountered that old following existing handlers were disappeared in 2.0.0/3.
    **on(event: 'connect', callback: Callback<Connect>): void;
    on(event: 'end', callback: Callback<End>): void;**

However new version supports only "error", "notice" & "notification" events. 
My question is: how it possible now to manage disconnection cases ? 
Is there reference to some more informative sample of a client code ?
Thanks.

**Comment by malthe** [comment]
It would seem that removing `on(event: 'end', callback: Callback): void` was a mistake because you're quite right that it's not possible to determine if a connection was disconnected out of band.

**Comment by malthe** [comment]
The fix is available in [v2.0.4](https://www.npmjs.com/package/ts-postgres/v/2.0.4).

**Comment by eugeneK1968** [comment]
Thanks for fix, it really helped and now it works as expected.
Just in case, in the process of moving from version 1.2.1 to 2.0.3 I have encountered a following issue with my tests (see screenshot). After long search I succeed to manage it on my side (by using @babel/preset-env with "transformIgnorePatterns" directive on ts-postgres), but it seems like something is wrong on ts-postgress side.  

![image](https://github.com/malthe/ts-postgres/assets/43238622/449829f0-83a2-4e33-9775-2e1238974b55)

**Comment by malthe** [comment]
One of the differences going to 2.x is that the library is now distributed as a [hybrid package](https://konstantinmuenster.medium.com/es-modules-all-you-need-to-know-9e6412780ae5), shipping with both ESM and CommonJS support.

This is supposed to "just work", but depending on your platform specifics, there could be some unexpected issues.

The environment setup that's tested automatically can be seen in the included [example projects](../tree/master/examples). I can't really advise on a specific environment configuration, there are too many ways you can incorporate this codebase to give an exhaustive answer.
