### ISSUE TITLE
Extend documentation - readme file ?

### ISSUE THREAD

**Issue by Maretzky85** [malthe/ts-postgres#13]
Hello, i find this project very useful, but i have some problems using it right.
Can You extend readme with how to do proper config on client - i know there was a Issue on that, but hey - do You really want to users go to issues page for how to drop in a config ?
Secondly - it may by my lack of knowledge, but i honestly don`t know how to paste arguments to query. There is an example, but it is unclear for me how to create that string, and how to use other values than string. Is there a standard that I`m not aware of ?

**Comment by malthe** [comment]
I have updated the README with a description of connection options and how to provide them as well as a section on passing query parameters.
