### ISSUE TITLE
Benchmark numbers available?

### ISSUE THREAD

**Issue by pedrolcn** [malthe/ts-postgres#15]
Hello, awesome looking project.
Was wondering if there are any benchmark numbers available, especially comparisons with other low-level postgres client libs in node such as [node-postgres](https://github.com/brianc/node-postgres) or [postgres.js](https://github.com/porsager/postgres). Performance would be a critical factor when deciding to migrate to a new lib.

**Comment by malthe** [comment]
I have used the following to benchmark the driver: https://github.com/MagicStack/pgbench
