### ISSUE TITLE
sum(column) is returned as null

### ISSUE THREAD

**Issue by bag-man** [malthe/ts-postgres#16]
If a `sum()` aggregate function is used, a null value is returned.

```typescript
import { Client } from 'ts-postgres';
import { equal } from 'assert';

export const testSum = async () => {
  const client = new Client({
    password: '123',
    host: 'localhost',
    user: 'postgres',
    port: 5432
  });

  await client.connect();

  await client.query(`
    DROP TABLE posts;
  `)

  await client.query(`
    CREATE TABLE posts (
      author text,
      postcount int
    );
  `)

  const authors = [
    { author: 'john', count: 10 },
    { author: 'john', count: 10 },
  ]

  client.query('BEGIN')

  authors.map(x => client.query(`
    INSERT INTO posts (author, postcount) VALUES ($1, $2);
  `, [ x.author, x.count ]))

  await client.query('COMMIT')

  const output = await client.query(`
    select sum(postcount) as total_comments, author from posts group by author;
  `)

  equal(output.rows[0][0], 20, 'Should equal 20 as post count is summed')

  await client.end()
}

const main = async () => {
  try {
    await testSum()
  } catch (err) {
    console.error(err)
    process.exit(1)
  }
}

main()

```

**Comment by malthe** [comment]
What happens if you await the BEGIN as well?

**Comment by bag-man** [comment]
Adding an await to the begin sadly didn't resolve the issue. 

I also found another bug, in that if the connection host / port are undefined or incorrect it doesn't throw or return anything interesting, it just hangs (I suppose waiting for a timeout?). It was quite frustrating having it just hang and no way to see what was wrong. 

Let me know if you want me to try any other tests :)

**Comment by malthe** [comment]
I'll try and replicate your setup in a regression test and also investigate the host/port undefined issue.

**Comment by bag-man** [comment]
Great thank you, so much!

I really appreciate the effort you've put into this.

**Comment by malthe** [comment]
If you don't expect a very large number (less than 32-bit signed), use `sum(postcount)::int` to get a result that fits in a JavaScript [Number](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Number_type) type.

I have fixed your issue by implementing support for the 64-bit signed data type, translating it to the [BigInt](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt) type.

**Comment by malthe** [comment]
Another point to make is that you should not leave promises dangling in Node. See https://palantir.github.io/tslint/rules/no-floating-promises/.

**Comment by bag-man** [comment]
Fantastic thank you so much! :D
