### ISSUE TITLE
About a query error

### ISSUE THREAD

**Issue by omempty** [malthe/ts-postgres#18]
Hello!
Thank you for releasing this wonderful module

By the way
I get an error when I request the following query
`
 SELECT TO_CHAR(public.tbl_result.endtime, 'HH24'), COUNT(*) AS pdt_count FROM public.tbl_result 
 GROUP BY TO_CHAR(public.tbl_result.endtime, 'HH24')
`

 => 
  **UnhandledPromiseRejectionWarning: TypeError: buffer.readBigInt64BE is not a function
    at read (D:\HelloTS\node_modules\ts-postgres\src\protocol.ts:306:39)**

On the other hand
When I run the query in module 'pg' or 'pg-promise', the query has no errors.

Please review the errors
 
---------------------------------------------
 		
Development environment: 
- PostgreSQL Ver.10.3 . WindowsServer2012
- VSCode with Typescript Ver.3.8.3. Windows8.1
- ts-postgres Ver.1.1.3

**Comment by malthe** [comment]
What's your version of node? Judging from your PostgreSQL install, looks like it might not be the most recent.

If you're on < 12, then a workaround (and you might want this anyway) is to cast the count to int:
```sql
SELECT TO_CHAR(public.tbl_result.endtime, 'HH24'), COUNT(*)::int AS pdt_count FROM public.tbl_result GROUP BY TO_CHAR(public.tbl_result.endtime, 'HH24')
```

**Comment by omempty** [comment]
> What's your version of node? Judging from your PostgreSQL install, looks like it might not be the most recent.
> 
> If you're on < 12, then a workaround (and you might want this anyway) is to cast the count to int:
> 
> ```sql
> SELECT TO_CHAR(public.tbl_result.endtime, 'HH24'), COUNT(*)::int AS pdt_count
> FROM public.tbl_result GROUP BY TO_CHAR(public.tbl_result.endtime, 'HH24')
> ```

Thanks for the quick response
The previous node version was v10.15.3 and after updating to the latest version, the query result works well without error.

Thank you again.

**Comment by vitaly-t** [comment]
> If you're on < 12

More correctly, if < 10.4.0, see [BigInt Notes](https://github.com/vitaly-t/pg-promise/wiki/BigInt).
