### ISSUE TITLE
await client.connect() never returns

### ISSUE THREAD

**Issue by scorbin** [malthe/ts-postgres#20]
I am trying to connect to a local postgres server running in a docker container with the code below.  It seems like it never returns or give and error.

import { Client } from 'ts-postgres';
import { ResultIterator } from 'ts-postgres/dist/src/result';

async function main() {
    const client = new Client({ "host": "localhost", "user": "postgres", "password": "postgres",   "database": "postgres" });
    try {
        await client.connect();
    } catch {
        console.log("something bad happend")
    }
    finally {
        await client.end();
    }
}

main()

**Comment by malthe** [comment]
What operating system? If this is MacOS or Windows, you might need to expose the service to the host system.

Are you able to connect using `psql` or `telnet localhost 5432` – ?

**Comment by scorbin** [comment]
@malthe you are right, after I exposed the port 5432 is works
docker run -p 5432:5432 --name postgres -e POSTGRES_PASSWORD=postgres -d postgres

**Comment by malthe** [comment]
Sounds good. I'll close this one out then.
