### ISSUE TITLE
es modules

### ISSUE THREAD

**Issue by chase-moskal** [malthe/ts-postgres#23]
hello! i'm from the future! :wave:

do you have plans to distribute modern es modules? maybe i could help!?

there will be more like me coming from whence i came — the rising tide of es modules will eventually consume all! *muahahah!*

**Comment by malthe** [comment]
Yes please!

**Comment by malthe** [comment]
@chase-moskal any progress on this? It is after all https://hacktoberfest.digitalocean.com/.

**Comment by malthe** [comment]
We've got ES module support since 1.9 (most of the work in ddfd3e63431fde7e7484d3b1fd1758168317d744), so I'm closing this out now.
