### ISSUE TITLE
jsonb column

### ISSUE THREAD

**Issue by javelinco** [malthe/ts-postgres#28]
Do I need to do anything special to insert/update a jsonb column in a Postgres database? I keep getting an escaped string. Here are some of the things I've tried:

Attempt #1:
```
const courseData = JSON.stringify(course);
await client.query(
   'INSERT INTO course (courseid, coursedata) VALUES ($1, $2) ON CONFLICT (courseid) DO UPDATE SET coursedata = $2',
   [courseId, courseData]
);
```

Attempt #2:
```
const courseData = JSON.stringify(course);
await client.query(
   'INSERT INTO course (courseid, coursedata) VALUES ($1, $2::jsonb) ON CONFLICT (courseid) DO UPDATE SET coursedata = $2::jsonb',
   [courseId, courseData]
);
```

Attempt #3:
```
      const courseData = JSON.stringify(course);
      await client.query(
        `INSERT INTO course (courseid, coursedata) VALUES ($1, $2) ON CONFLICT (courseid) DO UPDATE SET coursedata = $2`,
        [courseId, courseData],
        [DataType.Uuid, DataType.Jsonb]
      );
```

What am I doing wrong?

Thanks!

**Comment by malthe** [comment]
Don't stringify – just pass `course` where the query demands a `json` or `jsonb` type.

In some situations, you will need to type-cast (as you have done with `$2::jsonb`) but this depends on the query. PostgreSQL is often times able to determine the correct type and will send this type information back to the client.

**Comment by javelinco** [comment]
I should have mentioned that I tried that as well - but I'm using Typescript, and I get a type error. The error looks like this:

```
Type 'Course' is not assignable to type 'Value'.
  Type 'Course' is not assignable to type 'JsonMap'.
    Index signature is missing in type 'Course'.ts(2322)
```

Thank you for the assistance!

**Comment by malthe** [comment]
What happens if you explicitly cast it to `JsonMap`, e.g.
```typescript
import { JsonMap } from 'ts-postgres';

...
await client.query(sqlQuery, [courseId, <JsonMap> courseData]);
```
To be honest I never thought about this issue.

**Comment by javelinco** [comment]
That works! It looks a tiny bit different:

```
const sqlQuery = `INSERT INTO course (courseid, coursedata) VALUES ($1, $2) ON CONFLICT (courseid) DO UPDATE SET coursedata = $2`;
 await client.query(sqlQuery, [courseId, (course as unknown) as JsonMap]);
```

Thank you!

**Comment by malthe** [comment]
I'll close out the issue but will encourage comments that can improve upon this solution. There might be a more idiomatic way to express it than going via `unknown`.
