### ISSUE TITLE
Support for SSL/TLS

### ISSUE THREAD

**Issue by malthe** [malthe/ts-postgres#31]

**Comment by javelinco** [comment]
Do you have an approach that you are planning for this? I've been handed a requirement to use an SSL connection in the near future, and am willing to help, though I haven't really grocked the code base here.

**Comment by malthe** [comment]
@javelinco let me push the branch I already have for this – the reason I have been holding back on it is that when I ran the pipelined queries test against a remote database over SSL, there were unexpected errors (that do not show up running locally).

**Comment by javelinco** [comment]
Have you pushed the branch? What's it called?

**Comment by malthe** [comment]
@javelinco almost done – I ended up deciding to refactor some code and it's been in a state of 90% complete for a week. I'll try to get it done asap.

**Comment by javelinco** [comment]
No worries - just checking in!

**Comment by malthe** [comment]
@javelinco should work – but there are some issues with pipelining. I haven't been able to replicate these using a non-SSL connection.

**Comment by malthe** [comment]
Fixed in #35.
