### ISSUE TITLE
Using query to get a record with a DECIMAL(5,4) column

### ISSUE THREAD

**Issue by javelinco** [malthe/ts-postgres#32]
I've a table that has a DECIMAL(5,4) column. I'm attempting to use the following code to retrieve the contents of a record in that table:

```
const stream = client.query('SELECT * FROM coursestudent WHERE courseid = $1 AND studentId = $2', [courseId, studentId]);
for await (const dataRow of stream) {
    const courseStudentRecord: CourseStudentRecord = {
      courseId: (dataRow.get('courseid') as unknown) as string,
      studentId: (dataRow.get('studentid') as unknown) as string,
    };
    if (dataRow.get('quizscore') != null) {
      courseStudentRecord.quizScore = (dataRow.get('quizscore') as unknown) as number;
    }
}
```

The courseStudentRecord has the quizScore column defined as a number, and the courseId and studentId defined as strings.

**Here's the problem:** I expect the value in the column to populate the object (I can see it when I directly query the database), but the dataRow object shows the value of that column to be null. What do I need to do to get the data back properly?

Thanks!

**Comment by malthe** [comment]
I think perhaps the issue is that it's an unsupported data type. For a sanity check, try to cast the value to `text`.

**Comment by javelinco** [comment]
I'm actually looking to convert from a postgres DECIMAL(5,4) type to a typescript number. The column in the database is decimal - I don't need decimal in typescript, since that's covered by the number type. And that's where I'm running into trouble - the data consistently comes back as NULL from the query in the dataRow object.

**Comment by javelinco** [comment]
NOTE: I am, with some extra code, able to get the data back after converting the column data to TEXT in the query.

**Comment by malthe** [comment]
If you're wanting to put the decimal into a TypeScript `number` value then casting it to `double` should be fine too.

Why don't we support decimal by default? Well I suppose because floating point numbers are lossy compared to decimals. But perhaps it's better to have an option that would accept the loss of precision and just cast the value to a `number`.

**Comment by malthe** [comment]
See also https://github.com/tc39/proposal-decimal.
