### ISSUE TITLE
unable to do 2 queries into the same api call

### ISSUE THREAD

**Issue by phgachoud** [malthe/ts-postgres#33]
Trying to put things more in an object way I got the following function into a DbService which never inters into the `then` of the `lPromiseConnect`. I tried as below to avoid closing the connection `this._client.end()` seing if that was the reason but it didn't help.

Doing 2 `getResultset` calls from 2 api calls does work, but I'm trying do a select and then an insert. The select works, but the insert never enters into the `then` statement of `lPromiseConnect`.

`protected _client: Client

  constructor() {
    this._client = new Client(this._pgConfig)
  }

  /**
   * 
   * @param aQryS 
   */
  public getResultset(aQryS: string, aValuesArray?: any[]): Promise<Result> {
    let lRes: Promise<Result> = new Promise((aResolve, aReject) => {
      let lPromiseConnect: Promise<Connect> = this._client.connect()
      
      lPromiseConnect
        .then((lPgRes) => {
          //console.log("getResultset->connect()->lPgRes", lPgRes)// empty object
          let lQry: Query = new Query(aQryS, aValuesArray)
          try {
            this._client.query(lQry).then(
              (lQryRes) => {
                //this._client.end()
                console.log("getResultset->ok:", lQryRes)
                aResolve(lQryRes)
              },
              (lQryErr) => {
                //this._client.end()
                console.error("getResultset->qry_error:", lQryErr)
                aReject(lQryErr)
              }
            )
            .catch((lError) => {
                //this._client.end()
                console.error('getResultset->catch Error', lError)
                aReject(lError)
            })
          } catch (lTryCatchErr) {
            console.error("getResultset Error caught ->", lTryCatchErr)
            aReject(lTryCatchErr)
          }
        })
        .catch((lConnectionError) => {
          console.error("getResultset->connection catch error:", lConnectionError)
          //this._client.end()
          aReject(lConnectionError)
        })
    })

    return lRes
  }`

**Comment by phgachoud** [comment]
Note that if I recreate the client it works.... adding to my `getResultset` at the beginning `this._client = new Client(this._pgConfig)` but a client only usable 1 time?

**Comment by malthe** [comment]
@phgachoud you can format TypeScript code in issues using triple backtick "typescript":
<img width="108" alt="image" src="https://user-images.githubusercontent.com/26405/102797982-5ab04400-43a8-11eb-801c-f4fd969f16a4.png">

**Comment by malthe** [comment]
I think we can close this issue now that 1.2.0 has been released.
