### ISSUE TITLE
Changing connection properties

### ISSUE THREAD

**Issue by javelinco** [malthe/ts-postgres#4]
I'm confused about how I'm supposed to set the host, username, password, database, etc. for a given client. Why is the configuration readonly? Why does there not seem to be a way to inject the information I need to connect to the database server that I specify?

Am I misunderstanding how I'm supposed to connection to something besides a local database? If not, can we please have the "readonly" on the constructor property in the client removed?

Thank you.

**Comment by malthe** [comment]
The `Client` class takes an optional parameter:
```typescript
export interface Configuration {
    host?: string,
    port?: number,
    user?: string,
    database?: string,
    password?: string,
    types?: Map<DataType, ValueTypeReader>,
    extraFloatDigits?: number,
    keepAlive?: boolean,
    preparedStatementPrefix?: string
}
```
That is, you could do `client = Client({"host": ...})`. As for _readonly_, well you can't change these settings for a running client.
