### ISSUE TITLE
ts-postgres: RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 14. Received 16

### ISSUE THREAD

**Issue by seantcanavan** [malthe/ts-postgres#49]
Running into this error a few times and honestly not sure what's causing it. It seems to be non-deterministic. I've tried adding my requests in while loop to retry infinitely and it will make multiple attempts before succeeding and moving on.

EDIT: It appears to be under heavily multi-threaded conditions using 6 `Promise.all` calls to migrate a database from Postgres to MongoDB so we're trying to process one 'transaction' of records at a time and something is probably getting overwhelmed. Maybe the internal db cursor? Client connection pool?

EDIT2: This appears to be an issue with our remote RDS postgres instance engine `11.12` with default parameter group. Testing further. We're using `ts-postgres` `1.2.0`.

**Comment by malthe** [comment]
If you can write in pseudo-logic the sort of queries you're doing and how the promise waiting is done, then I can try and replicate in a test case.

**Comment by seantcanavan** [comment]
It's happening on our initial get query every time now so we've resorted to the following:

* disable writes in production
* run `pg dump` on production database
* load the `pg dump` on local
* run the migration script from local postgres to prod mongodb

At this point I think the issue is definitely with the prod postgres instance and/or the `ts-postgres` interaction with said prod database. I'm going to try a few more things today.

I will say the first time we encountered this error it was when using `select *` on our tables. We had to resort to using `select col1, col2, col3, col4,...` etc on every table.

**Comment by malthe** [comment]
I think I have managed to reproduce this issue locally.

**Comment by malthe** [comment]
@seantcanavan do you have a stack trace that points to the exact line in the code which throws the error?

**Comment by seantcanavan** [comment]
@malthe what's the best way to get that stack trace? The `.query` calls appear to be immune to `try/catch`.

**Comment by malthe** [comment]
@seantcanavan I think if you add the following before this line: https://github.com/malthe/ts-postgres/blob/1.2.0/src/client.ts#L377:

```typescript
console.log(error.stack)
```
Then that ought to print the stack trace from the point of the exception.

That is, the code would read:
```typescript
try {
    const read = this.receive(buffer, this.offset, size);
    this.offset += read;
    remaining = size - read;
} catch (error) {
    logger.warn(error);
    console.log(error.stack);
    this.stream.destroy();
}
```

**Comment by seantcanavan** [comment]
@malthe I'll work on this first thing Monday morning. Thanks!

**Comment by seantcanavan** [comment]
I've been struggling significantly with the `not in ($1)` syntax. There's no documentation on how to use `not in` with this library. If I do:

```
            await this.client.query(
                `SELECT ${this.columns} FROM table WHERE id NOT IN ($1)`,
                [first_wave],
                [DataType.ArrayInt4]
            )
```
I get: `(node:56320) UnhandledPromiseRejectionWarning: Error: operator does not exist: integer <> integer[]`

When `[first_wave]` = `[1, 2, 3]`

**Comment by malthe** [comment]
You need to use `WHERE NOT id = ANY ($1)` – this has to do with set vs array logic in PostgreSQL – or alternatively, `WHERE id != ALL ($1)`.

The `types` argument shouldn't be necessary since PostgreSQL already knows that `id` is an integer. Try omitting it and see if it doesn't work just fine without explicitly denoting the type of the parameter.

**Comment by malthe** [comment]
@seantcanavan can you release 1.2.1 – there's a bugfix in there that might solve your `RangeError` issue.

**Comment by seantcanavan** [comment]
I'm using `1.2.1` right now without issue - thanks! Eventually I plan to expand the column selection to add back more columns to try to replicate the original error again. Also I have to thank you sincerely for helping me with my syntax. I'm on round 2 of 3 for our production data migration and things are going smoothly :crossed_fingers:

**Comment by malthe** [comment]
Sounds great! Thanks for reporting this issue.
