### ISSUE TITLE
Support for `checkServerIdentity`?

### ISSUE THREAD

**Issue by evanmiller** [malthe/ts-postgres#69]
Hello, we're trying to port some code from `pg` and one of the features we need is a custom `checkServerIdentity` override (see https://nodejs.org/api/tls.html#tlsconnectoptions-callback). I was thinking we could accomplish this by:

* Changing `SecureContextOptions` to `ConnectionOptions` (which extends `SecureContextOptions`)
* Adding `ssl.checkServerIdentity` to the `options` passed to `connect` (aka `tls`) in client.ts

Does this sound reasonable? Happy to prep a PR.

**Comment by malthe** [comment]
Seems reasonable enough. Is there a good reason to do something like that – mostly just thinking about how this would be described in the change notes.

**Comment by evanmiller** [comment]
Sure – if a server is behind a load-balancer, we want to check that the `subjectaltname` on the certificate matches a whitelist. Here is a use-case described by the "other" driver: https://github.com/brianc/node-postgres/issues/1185
