### ISSUE TITLE
Preparing incorrect statement hangs for ever

### ISSUE THREAD

**Issue by ericvergnaud** [malthe/ts-postgres#72]
See enclosed test file:
 - preparing a valid statement works as expected
 - preparing an invalid one hangs forever
The expectation is that preparing an invalid statement will throw an error than can be used to troubleshoot the issue

FWIW using `result = await client.query(...)` does throw an error if the query is invalid

[TsClient.test.ts.zip](https://github.com/malthe/ts-postgres/files/13217639/TsClient.test.ts.zip)

**Comment by malthe** [comment]
Fix available in [1.4.0](https://www.npmjs.com/package/ts-postgres/v/1.4.0).

**Comment by ericvergnaud** [comment]
Thanks! Much appreciate the reactivity :-)
