### ISSUE TITLE
connect not in exports

### ISSUE THREAD

**Issue by lifeiscontent** [malthe/ts-postgres#99]
in the 1.9.0 version `connect` is not in the exports of the d.ts file https://www.npmjs.com/package/ts-postgres?activeTab=code

**Comment by malthe** [comment]
It's because `connect` will be the new interface starting from 2.0 (unreleased).

I'm waiting for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68313/ to get merged before a release.

**Comment by malthe** [comment]
2.0.0 released: https://www.npmjs.com/package/ts-postgres/v/2.0.0.

**Comment by lifeiscontent** [comment]
@malthe fwiw there's no release on GitHub. Might want to do that 😅

**Comment by malthe** [comment]
Thanks – done now, https://github.com/malthe/ts-postgres/releases/tag/2.0.0 – !
